baseurl = "https://blog.diamondb.xyz"
languageCode = "en"
title = "diamondburned's stupid blog posts"
theme = "burned"
description = "where I shitpost"

[params]
	icon = "images/icon.png" # favicon
	footer = "Discord: `_diamondburned_#4507`"
	author = "diamondburned"

[params.tweaks]
	fonts = ["Source Sans Pro", "Noto Sans", "Helvetica", "Segoe UI"]
	blend = "false" # blending body with the background
	stretchbar = "false" # stretching the navbar to fullwidth
	floatingbar = "true" # makes the bar float
	darkshadowbar = "false" # use dark shadow instead
	credits = "true" # show credit
	fontawesome = "true" # use fontawesome, required for `icon` to work

[params.home] # Homepage
	text = ""
	icon = "fas fa-home"

[params.about] # Website, comment block to de-activate
	text = ""
	icon = "fas fa-info-circle"
	url = "https://diamondb.xyz/"

#[params.github]
#	username = "diamondburned"
#	text = ""
#	icon = "fab fa-github"

[params.gitlab]
	username = "diamondburned"
	text = ""
	icon = "fab fa-gitlab"

[params.mail]
	address = "diamondburned@diamondb.xyz"
	text = ""
	icon = "fas fa-envelope"

#[params.twitter]
#	username = "diamondburned"
#	text = ""
#	icon = "fab fa-twitter"